#      ______                         __
#     /      \                       |  \
#    |  $$$$$$\ __    __   _______  _| $$_     ______   ______ ____
#    | $$   \$$|  \  |  \ /       \|   $$ \   /      \ |      \    \
#    | $$      | $$  | $$|  $$$$$$$ \$$$$$$  |  $$$$$$\| $$$$$$\$$$$\
#    | $$   __ | $$  | $$ \$$    \   | $$ __ | $$  | $$| $$ | $$ | $$
#    | $$__/  \| $$__/ $$ _\$$$$$$\  | $$|  \| $$__/ $$| $$ | $$ | $$
#     \$$    $$ \$$    $$|       $$   \$$  $$ \$$    $$| $$ | $$ | $$
#      \$$$$$$   \$$$$$$  \$$$$$$$     \$$$$   \$$$$$$  \$$  \$$  \$$
#     ______
#    |      \
#     \$$$$$$ ______ ____    ______    ______    ______
#      | $$  |      \    \  |      \  /      \  /      \
#      | $$  | $$$$$$\$$$$\  \$$$$$$\|  $$$$$$\|  $$$$$$\
#      | $$  | $$ | $$ | $$ /      $$| $$  | $$| $$    $$
#     _| $$_ | $$ | $$ | $$|  $$$$$$$| $$__| $$| $$$$$$$$
#    |   $$ \| $$ | $$ | $$ \$$    $$ \$$    $$ \$$     \
#     \$$$$$$ \$$  \$$  \$$  \$$$$$$$ _\$$$$$$$  \$$$$$$$
#                                    |  \__| $$
#                                     \$$    $$
#                                      \$$$$$$
#     ________  __                                                        __
#    |        \|  \                                                      |  \
#    | $$$$$$$$ \$$  ______    ______   __   __   __   ______    ______  | $$   __   _______
#    | $$__    |  \ /      \  /      \ |  \ |  \ |  \ /      \  /      \ | $$  /  \ /       \
#    | $$  \   | $$|  $$$$$$\|  $$$$$$\| $$ | $$ | $$|  $$$$$$\|  $$$$$$\| $$_/  $$|  $$$$$$$
#    | $$$$$   | $$| $$   \$$| $$    $$| $$ | $$ | $$| $$  | $$| $$   \$$| $$   $$  \$$    \
#    | $$      | $$| $$      | $$$$$$$$| $$_/ $$_/ $$| $$__/ $$| $$      | $$$$$$\  _\$$$$$$\
#    | $$      | $$| $$       \$$     \ \$$   $$   $$ \$$    $$| $$      | $$  \$$\|       $$
#     \$$       \$$ \$$        \$$$$$$$  \$$$$$\$$$$   \$$$$$$  \$$       \$$   \$$ \$$$$$$$
#     __                        _______             __        __
#    |  \                      |       \           |  \      |  \
#    | $$____   __    __       | $$$$$$$\  ______  | $$   __  \$$
#    | $$    \ |  \  |  \      | $$  | $$ |      \ | $$  /  \|  \
#    | $$$$$$$\| $$  | $$      | $$  | $$  \$$$$$$\| $$_/  $$| $$
#    | $$  | $$| $$  | $$      | $$  | $$ /      $$| $$   $$ | $$
#    | $$__/ $$| $$__/ $$      | $$__/ $$|  $$$$$$$| $$$$$$\ | $$
#    | $$    $$ \$$    $$      | $$    $$ \$$    $$| $$  \$$\| $$
#     \$$$$$$$  _\$$$$$$$       \$$$$$$$   \$$$$$$$ \$$   \$$ \$$
#              |  \__| $$
#               \$$    $$
#                \$$$$$$